#!/usr/bin/env bash

set -Eeuo pipefail

ADMIN_EMAIL="admin@sub2api.local"
ADMIN_PASSWORD=""
SERVER_PORT="18080"
TZ_VALUE="Asia/Shanghai"
DEPLOY_BASE="/opt/sub2api"
SKIP_FIREWALL="0"
NO_BUILD_CACHE="0"

log() {
  printf '[INFO] %s\n' "$*"
}

warn() {
  printf '[WARN] %s\n' "$*" >&2
}

die() {
  printf '[ERROR] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash deploy/rocky-deploy.sh [options]

Options:
  --admin-email <email>       Admin email. Default: admin@sub2api.local
  --admin-password <password> Admin password. Default: auto-generated by app
  --port <port>               Published HTTP port. Default: 18080
  --tz <timezone>             Timezone. Default: Asia/Shanghai
  --deploy-dir <path>         Deployment base directory. Default: /opt/sub2api
  --skip-firewall             Do not open firewall port automatically
  --no-build-cache            Build image without Docker cache
  --help                      Show this message
EOF
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "Please run this script as root."
  fi
}

detect_os() {
  if [[ ! -f /etc/os-release ]]; then
    die "/etc/os-release not found."
  fi

  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}" in
    rocky|rhel|almalinux|centos)
      ;;
    *)
      warn "This script is tuned for Rocky/RHEL family, current ID=${ID:-unknown}."
      ;;
  esac
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

install_base_packages() {
  log "Installing base packages..."
  dnf -y install dnf-plugins-core curl git openssl tar >/dev/null
}

install_docker() {
  if command_exists docker && docker compose version >/dev/null 2>&1; then
    log "Docker Engine and Compose plugin already installed."
  else
    log "Installing Docker Engine and Compose plugin..."
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo >/dev/null
    dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  fi

  log "Enabling Docker service..."
  systemctl enable --now docker
}

ensure_firewall_port() {
  if [[ "${SKIP_FIREWALL}" == "1" ]]; then
    log "Skipping firewall changes."
    return
  fi

  if ! systemctl is-active firewalld >/dev/null 2>&1; then
    warn "firewalld is not active, skip opening port ${SERVER_PORT}."
    return
  fi

  log "Opening firewall port ${SERVER_PORT}/tcp..."
  firewall-cmd --permanent --add-port="${SERVER_PORT}/tcp" >/dev/null
  firewall-cmd --reload >/dev/null
}

escape_sed_replacement() {
  printf '%s' "$1" | sed 's/[\/&|]/\\&/g'
}

upsert_env() {
  local file="$1"
  local key="$2"
  local value="$3"
  local escaped

  escaped="$(escape_sed_replacement "$value")"
  if grep -q "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${escaped}|" "$file"
  else
    printf '%s=%s\n' "$key" "$value" >>"$file"
  fi
}

prepare_env_file() {
  local env_example="$1"
  local env_file="$2"

  if [[ ! -f "${env_example}" ]]; then
    die "Missing env example: ${env_example}"
  fi

  if [[ ! -f "${env_file}" ]]; then
    log "Creating deploy/.env from template..."
    cp "${env_example}" "${env_file}"
  else
    log "Using existing deploy/.env."
  fi

  if ! grep -Eq '^POSTGRES_PASSWORD=change_this_secure_password$' "${env_file}" && \
     ! grep -Eq '^POSTGRES_PASSWORD=$' "${env_file}"; then
    :
  else
    upsert_env "${env_file}" "POSTGRES_PASSWORD" "$(openssl rand -hex 32)"
  fi

  if grep -Eq '^JWT_SECRET=$' "${env_file}"; then
    upsert_env "${env_file}" "JWT_SECRET" "$(openssl rand -hex 32)"
  fi

  if grep -Eq '^TOTP_ENCRYPTION_KEY=$' "${env_file}"; then
    upsert_env "${env_file}" "TOTP_ENCRYPTION_KEY" "$(openssl rand -hex 32)"
  fi

  upsert_env "${env_file}" "ADMIN_EMAIL" "${ADMIN_EMAIL}"
  upsert_env "${env_file}" "SERVER_PORT" "${SERVER_PORT}"
  upsert_env "${env_file}" "TZ" "${TZ_VALUE}"
  upsert_env "${env_file}" "BIND_HOST" "127.0.0.1"
  upsert_env "${env_file}" "APP_DATA_DIR" "${DEPLOY_BASE}/data/app"
  upsert_env "${env_file}" "POSTGRES_DATA_DIR" "${DEPLOY_BASE}/data/postgres"
  upsert_env "${env_file}" "REDIS_DATA_DIR" "${DEPLOY_BASE}/data/redis"

  if [[ -n "${ADMIN_PASSWORD}" ]]; then
    upsert_env "${env_file}" "ADMIN_PASSWORD" "${ADMIN_PASSWORD}"
  fi

  chmod 600 "${env_file}"
}

deploy_project() {
  local repo_root="$1"
  local compose_file="$2"
  local env_file="$3"

  mkdir -p "${DEPLOY_BASE}/data/app" "${DEPLOY_BASE}/data/postgres" "${DEPLOY_BASE}/data/redis"

  log "Building and starting containers..."
  if [[ "${NO_BUILD_CACHE}" == "1" ]]; then
    docker compose --env-file "${env_file}" -f "${compose_file}" build --no-cache
  fi

  docker compose --env-file "${env_file}" -f "${compose_file}" up -d --build
}

print_summary() {
  local repo_root="$1"
  local env_file="$2"
  local host_ip

  host_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [[ -z "${host_ip}" ]]; then
    host_ip="SERVER_IP"
  fi

  log "Deployment completed."
  printf 'Deploy base: %s\n' "${DEPLOY_BASE}"
  printf 'Project root: %s\n' "${repo_root}"
  printf 'Compose file: %s\n' "${repo_root}/deploy/docker-compose.current.yml"
  printf 'Env file: %s\n' "${env_file}"
  printf 'URL: http://%s:%s\n' "${host_ip}" "${SERVER_PORT}"
  printf 'Logs: docker compose --env-file %s -f %s logs -f sub2api\n' "${env_file}" "${repo_root}/deploy/docker-compose.current.yml"

  if [[ -n "${ADMIN_PASSWORD}" ]]; then
    printf 'Admin: %s / %s\n' "${ADMIN_EMAIL}" "${ADMIN_PASSWORD}"
  else
    printf 'Admin: %s / auto-generated in logs on first startup\n' "${ADMIN_EMAIL}"
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --admin-email)
        ADMIN_EMAIL="$2"
        shift 2
        ;;
      --admin-password)
        ADMIN_PASSWORD="$2"
        shift 2
        ;;
      --port)
        SERVER_PORT="$2"
        shift 2
        ;;
      --tz)
        TZ_VALUE="$2"
        shift 2
        ;;
      --deploy-dir)
        DEPLOY_BASE="$2"
        shift 2
        ;;
      --skip-firewall)
        SKIP_FIREWALL="1"
        shift
        ;;
      --no-build-cache)
        NO_BUILD_CACHE="1"
        shift
        ;;
      --help)
        usage
        exit 0
        ;;
      *)
        die "Unknown option: $1"
        ;;
    esac
  done
}

main() {
  local script_dir repo_root compose_file env_example env_file

  parse_args "$@"
  require_root
  detect_os

  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  repo_root="$(cd "${script_dir}/.." && pwd)"
  compose_file="${repo_root}/deploy/docker-compose.current.yml"
  env_example="${repo_root}/deploy/.env.example"
  env_file="${repo_root}/deploy/.env"

  [[ -f "${compose_file}" ]] || die "Missing compose file: ${compose_file}"
  install_base_packages
  install_docker
  ensure_firewall_port
  prepare_env_file "${env_example}" "${env_file}"
  deploy_project "${repo_root}" "${compose_file}" "${env_file}"
  print_summary "${repo_root}" "${env_file}"
}

main "$@"
